### ISSUE TITLE
Image Viewer crashes 

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-imageanalytics#195]
##### Image Analytics version

0.6.0

##### Orange version

3.29.dev

##### Expected behavior
No crash.

##### Actual behavior
```
----------------------------- KeyError Exception ------------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimageviewer.py", line 1115, in onSelectionChanged
    self.commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1730, in unconditional_commit
    do_commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1738, in do_commit
    commit()
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimageviewer.py", line 1127, in commit
    self.Outputs.selected_data.send(None)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/utils/signals.py", line 388, in send
    signal_manager.send(self.widget, self.name, value, *extra_args)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 750, in send
    super().send(node, channel, value)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 500, in send
    state = self.__node_outputs[node][channel]
KeyError: SchemeNode(description_id='orangecontrib.imageanalytics.widgets.owimageviewer', title='Image Viewer', ...)
-------------------------------------------------------------------------------

```

##### Steps to reproduce the behavior
I think it happens when the image URL is wrong and the widget still tries to download images from the internet, but the widget is then deleted.

**Comment by PrimozGodec** [comment]
This error seems very strange (it looks like the output node is not in the dictionary); I am not sure if it has anything to do with data (or missing image). @ajda, can you reproduce it? I cannot come up with the reason for it. Maybe @ales-erjavec has any idea?

**Comment by ajdapretnar** [comment]
No, I cannot anymore. I will close it for now.
