### ISSUE TITLE
Image Embedding Error NOW

### ISSUE THREAD

**Issue by infohoon** [biolab/orange3-imageanalytics#42]
Before traffic sign example is working. Now, It's not working.

Image file not found error is occurred, but image url is good.
just Image Embedding block is not working.

**Comment by ajdapretnar** [comment]
I can't reproduce this. Which version of ImageAnalytics do you have?

**Comment by japulickal** [comment]
Image Embedding widget is missing in the widget tray. 

Orange version 3.4.2
Git version : f3076cd
OS: OS X EL Captitan (10.11.6)

Installation Log
`Collecting Orange3-ImageAnalytics
Requirement already satisfied: Orange3>=3.3.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: lockfile in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: cachecontrol in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: hyper==0.7.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: requests in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: numpy>=1.10.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: Pillow>=2.7.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: AnyQt>=0.0.6 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: bottleneck>=1.0.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: chardet>=2.3.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: dill in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: docutils in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: joblib>=0.9.4 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: keyring in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: keyrings.alt in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: pyqtgraph>=0.10.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: scikit-learn>=0.18.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: scipy>=0.11.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: setuptools>=11.3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: xlrd>=0.9.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: msgpack-python in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from cachecontrol->Orange3-ImageAnalytics)
Requirement already satisfied: hyperframe<4.0,>=3.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from hyper==0.7.0->Orange3-ImageAnalytics)
Requirement already satisfied: h2<3.0,>=2.4 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from hyper==0.7.0->Orange3-ImageAnalytics)
Requirement already satisfied: idna<2.6,>=2.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->Orange3-ImageAnalytics)
Requirement already satisfied: certifi>=2017.4.17 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->Orange3-ImageAnalytics)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->Orange3-ImageAnalytics)
Requirement already satisfied: olefile in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Pillow>=2.7.0->Orange3-ImageAnalytics)
Requirement already satisfied: six in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from keyrings.alt->Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: hpack<4,>=2.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from h2<3.0,>=2.4->hyper==0.7.0->Orange3-ImageAnalytics)
Installing collected packages: Orange3-ImageAnalytics
Successfully installed Orange3-ImageAnalytics-0.1.7`

**Comment by ales-erjavec** [comment]
> Image Embedding widget is missing in the widget tray. 

The error causing this is:
```
Error while importing 'orangecontrib.imageanalytics.widgets.owimageembedding'.
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/__init__.py", line 70, in <module>
    assert major == 3
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/imageanalytics/widgets/owimageembedding.py", line 21, in <module>
    from orangecontrib.imageanalytics.image_embedder import ImageEmbedder
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/imageanalytics/image_embedder.py", line 11, in <module>
    import requests
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/__init__.py", line 74, in <module>
    raise RuntimeError('Requests dependency \'chardet\' must be version >= 3.0.2, < 3.1.0!')
RuntimeError: Requests dependency 'chardet' must be version >= 3.0.2, < 3.1.0!
```

Ultimately this is caused by pip not having a proper dependency resolver.

**Comment by ph4nie** [comment]
Hi,
I also have a problem with Image Embedding widget. When I input images from the Import Images widget (which seems to work), the second block shows a warning sign, and say 'click Apply to try again'.

Any ideas to solve this ? Thanks !

**Comment by inejc** [comment]
@ph4nie the warning sign indicates that there are problems with server connection. Make sure you are connected to the internet when using the Image Embedding widget. If that's not the problem, please tell us which version of the add-on you are using and attach the logs (click on **View -> Log**).

**Comment by ph4nie** [comment]
My internet connection works fine for every other task.
I'm using  Image Analytics add-on version 0.1.7
Here is the log I get : 
Error when disconnecting from server
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 90, in _send_request
    headers=headers
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 281, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 559, in endheaders
    stream.send_data(message_body, final)
  File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 126, in send_data
    self._send_chunk(chunk, final)
  File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 338, in _send_chunk
    self._send_outstanding_data()
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 466, in _send_outstanding_data
    self._send_cb(data, tolerate_peer_gone=tolerate_peer_gone)
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 622, in _send_cb
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 43, in disconnect_from_server
    self._server_connection.close()
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 441, in close
    stream.close(error_code)
  File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 297, in close
    self._send_outstanding_data(tolerate_peer_gone=True)
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 466, in _send_outstanding_data
    self._send_cb(data, tolerate_peer_gone=tolerate_peer_gone)
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 622, in _send_cb
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
Request sending failed
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 90, in _send_request
    headers=headers
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 281, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 559, in endheaders
    stream.send_data(message_body, final)
  File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 126, in send_data
    self._send_chunk(chunk, final)
  File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 338, in _send_chunk
    self._send_outstanding_data()
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 466, in _send_outstanding_data
    self._send_cb(data, tolerate_peer_gone=tolerate_peer_gone)
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 622, in _send_cb
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
Error
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\widgets\owimageembedding.py", line 240, in __set_results
    embeddings = f.result()
  File "C:\Python34\lib\concurrent\futures\_base.py", line 395, in result
    return self.__get_result()
  File "C:\Python34\lib\concurrent\futures\_base.py", line 354, in __get_result
    raise self._exception
  File "C:\Python34\lib\site-packages\Orange\widgets\utils\concurrent.py", line 144, in run
    result = self.func(*self.args, **self.kwargs)
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\widgets\owimageembedding.py", line 195, in run_embedding
    file_paths=paths, image_processed_callback=advance)
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\image_embedder.py", line 126, in __call__
    batch, image_processed_callback
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\image_embedder.py", line 192, in _send_to_server
    body_bytes=image
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 95, in _send_request
    raise error
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 90, in _send_request
    headers=headers
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 281, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 559, in endheaders
    stream.send_data(message_body, final)
  File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 126, in send_data
    self._send_chunk(chunk, final)
  File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 338, in _send_chunk
    self._send_outstanding_data()
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 466, in _send_outstanding_data
    self._send_cb(data, tolerate_peer_gone=tolerate_peer_gone)
  File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 622, in _send_cb
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte

**Comment by inejc** [comment]
@ph4nie I have opened a separate issue, see https://github.com/biolab/orange3-imageanalytics/issues/50.

**Comment by PrimozGodec** [comment]
I am closing this issue due to inactivity. I also think that bug should go since the library that manages connections was updated https://github.com/biolab/orange3-imageanalytics/pull/97. I bug still exist you are welcome to reopen the issue.
