### ISSUE TITLE
Image Embedding: ConnectionAbortedError on Windows

### ISSUE THREAD

**Issue by inejc** [biolab/orange3-imageanalytics#50]
**ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine**

> @ph4nie wrote: When I input images from the Import Images widget (which seems to work), the second block shows a warning sign, and say 'click Apply to try again'. ... I'm using Image Analytics add-on version 0.1.7
Here is the log I get :

```
Error when disconnecting from server
Traceback (most recent call last):
File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 90, in _send_request
headers=headers
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 281, in request
self.endheaders(message_body=body, final=True, stream_id=stream_id)
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 559, in endheaders
stream.send_data(message_body, final)
File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 126, in send_data
self._send_chunk(chunk, final)
File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 338, in _send_chunk
self._send_outstanding_data()
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 466, in _send_outstanding_data
self._send_cb(data, tolerate_peer_gone=tolerate_peer_gone)
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 622, in _send_cb
self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 43, in disconnect_from_server
self._server_connection.close()
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 441, in close
stream.close(error_code)
File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 297, in close
self._send_outstanding_data(tolerate_peer_gone=True)
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 466, in _send_outstanding_data
self._send_cb(data, tolerate_peer_gone=tolerate_peer_gone)
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 622, in _send_cb
self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
Request sending failed
Traceback (most recent call last):
File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 90, in _send_request
headers=headers
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 281, in request
self.endheaders(message_body=body, final=True, stream_id=stream_id)
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 559, in endheaders
stream.send_data(message_body, final)
File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 126, in send_data
self._send_chunk(chunk, final)
File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 338, in _send_chunk
self._send_outstanding_data()
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 466, in _send_outstanding_data
self._send_cb(data, tolerate_peer_gone=tolerate_peer_gone)
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 622, in _send_cb
self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
Error
Traceback (most recent call last):
File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\widgets\owimageembedding.py", line 240, in __set_results
embeddings = f.result()
File "C:\Python34\lib\concurrent\futures_base.py", line 395, in result
return self.__get_result()
File "C:\Python34\lib\concurrent\futures_base.py", line 354, in __get_result
raise self._exception
File "C:\Python34\lib\site-packages\Orange\widgets\utils\concurrent.py", line 144, in run
result = self.func(*self.args, **self.kwargs)
File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\widgets\owimageembedding.py", line 195, in run_embedding
file_paths=paths, image_processed_callback=advance)
File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\image_embedder.py", line 126, in call
batch, image_processed_callback
File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\image_embedder.py", line 192, in _send_to_server
body_bytes=image
File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 95, in _send_request
raise error
File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 90, in _send_request
headers=headers
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 281, in request
self.endheaders(message_body=body, final=True, stream_id=stream_id)
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 559, in endheaders
stream.send_data(message_body, final)
File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 126, in send_data
self._send_chunk(chunk, final)
File "C:\Python34\lib\site-packages\hyper\http20\stream.py", line 338, in _send_chunk
self._send_outstanding_data()
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 466, in _send_outstanding_data
self._send_cb(data, tolerate_peer_gone=tolerate_peer_gone)
File "C:\Python34\lib\site-packages\hyper\http20\connection.py", line 622, in _send_cb
self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
```

**Comment by ndkazu** [comment]
Hello,
I am using orange 3.11 on windows7, and I have the same issue. Anything new?
Kazu

**Comment by ndkazu** [comment]
Hello, 
I am using version 0.2.0 of the add-on. I don't know if this is related, but i get the following error message every times I start Orange3
`C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
from pandas.core import datetools
Error while importing 'orangecontrib.textable_prototypes.widgets.EighteenthCenturyPoetry'. The widget will not be shown.
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\textable_prototypes\widgets\EighteenthCenturyPoetry.py", line 458
regexes=re.compile(r"
(.+?)
"),
^
SyntaxError: invalid syntax
Error while importing 'orangecontrib.textable_prototypes.widgets.OWTextableTheatreClassique'. The widget will not be shown.
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\textable_prototypes\widgets\OWTextableTheatreClassique.py", line 417
conditions={u'id': re.compile(ur'^table_AA$')},
^
SyntaxError: invalid syntax
C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\gensim\utils.py:1167: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Error while importing 'orangecontrib.prototypes.widgets.owface'. The widget will not be shown.
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\prototypes\widgets\owface.py", line 7, in 
import cv2
ModuleNotFoundError: No module named 'cv2'
Error while importing 'orangecontrib.prototypes.widgets.owfeaturestatistics'. The widget will not be shown.
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\prototypes\widgets\owfeaturestatistics.py", line 31, in 
from orangecontrib.prototypes.widgets.utils.histogram import Histogram
ModuleNotFoundError: No module named 'orangecontrib.prototypes.widgets.utils.histogram'
Error while importing 'orangecontrib.prototypes.widgets.owparallelcoordinates'. The widget will not be shown.
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\prototypes\widgets\owparallelcoordinates.py", line 15, in 
from orangecontrib.prototypes.widgets.utils.plotly_widget import Plotly
ModuleNotFoundError: No module named 'orangecontrib.prototypes.widgets.utils.plotly_widget'
Error while importing 'orangecontrib.prototypes.widgets.owwebcamcapture'. The widget will not be shown.
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\prototypes\widgets\owwebcamcapture.py", line 7, in 
import cv2
ModuleNotFoundError: No module named 'cv2'
An ImportError occurred while loading entry point 'Audio - IJS = orangecontrib.audio.widgets'
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\canvas\registry\discovery.py", line 89, in run
point = entry_point.resolve()
File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'orangecontrib.audio'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orange3-example-addon.readthedocs.io/en/latest/')'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orange3-prototypes.readthedocs.io/en/latest/')'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orange3-text.readthedocs.io/en/latest/')'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orange3-timeseries.readthedocs.io/en/latest/')'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orange3-educational.readthedocs.io/en/latest/')'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orange3-datafusion.readthedocs.io/en/latest/')'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('https://docs.orange.biolab.si/3/visual-programming/')'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orange3-associate.readthedocs.io/en/latest/')'
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orange3-textable-prototypes.readthedocs.io/en/latest/')'
`

**Comment by PrimozGodec** [comment]
Ok, I will take a close look at the issue. @ndkazu can I just ask you to copy the complete error message when the issue occurs.

**Comment by ndkazu** [comment]
Hello,

I am sending the complete error:

`
(C:\ProgramData\Anaconda2\envs\Pyt3) C:\Users\2114122>orange-canvas
QWidget::setWindowModified: The window title does not contain a '[*]' placeholde
r
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('https://docs
.orange.biolab.si/3/visual-programming/')'
Remote server not reachable
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\image
analytics\http2_client.py", line 76, in _server_ping_successful
    self._server_connection.ping(bytes(8))
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\hypertemp\http20\co
nnection.py", line 214, in ping
    self.connect()
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\hypertemp\http20\co
nnection.py", line 374, in connect
    timeout=connect_timeout)
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\socket.py", line 704, in create_c
onnection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\socket.py", line 745, in getaddri
nfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
Remote server not reachable
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\image
analytics\http2_client.py", line 76, in _server_ping_successful
    self._server_connection.ping(bytes(8))
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\hypertemp\http20\co
nnection.py", line 214, in ping
    self.connect()
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\hypertemp\http20\co
nnection.py", line 374, in connect
    timeout=connect_timeout)
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\socket.py", line 704, in create_c
onnection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\socket.py", line 745, in getaddri
nfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
Error
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\image
analytics\widgets\owimageembedding.py", line 286, in __set_results
    embeddings = f.result()
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\concurrent\futures\_base.py", lin
e 425, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\concurrent\futures\_base.py", lin
e 384, in __get_result
    raise self._exception
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\Orange\widgets\util
s\concurrent.py", line 173, in run
    result = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\image
analytics\widgets\owimageembedding.py", line 238, in run_embedding
    file_paths=paths, image_processed_callback=advance)
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\image
analytics\image_embedder.py", line 165, in __call__
    return self.from_file_paths(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\image
analytics\image_embedder.py", line 224, in from_file_paths
    b_images, image_processed_callback, repeats_counter
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\image
analytics\image_embedder.py", line 301, in _send_to_server
    body_bytes=image
  File "C:\ProgramData\Anaconda2\envs\Pyt3\lib\site-packages\orangecontrib\image
analytics\http2_client.py", line 84, in _send_request
    raise ConnectionError(self._no_conn_err)
ConnectionError: No connection with server, call reconnect_to_server()
`

**Comment by BlazZupan** [comment]
Are you behind the firewall and are using proxy to access the internet?

**Comment by ndkazu** [comment]
Hello,
Yes I am behind a firewall using a proxy.

**Comment by PrimozGodec** [comment]
After the upgrade of Hyper library, we made last week there is an option to support proxies. Done in https://github.com/biolab/orange3-imageanalytics/pull/101

**Comment by ndkazu** [comment]
Hello,
Is there any progress concerning this issue?
Thanks
Kazu

**Comment by PrimozGodec** [comment]
Hello, the fix is made https://github.com/biolab/orange3-imageanalytics/pull/101 but is waiting for a test. Sorry for the delay, we really want to make sure it 100% work before we release it.

If you need the fix urgently you can download the fixed version from the pull request https://github.com/biolab/orange3-imageanalytics/pull/101 and install it manually.

**Comment by ndkazu** [comment]
Thank you for your answer. I will wait for the end of the testing phase.

Kazu

**Comment by PrimozGodec** [comment]
Hello @ndkazu ,

the proxy fix is now merged in master. Until the release is made you can install the fixed version from the master of this repository. The instructions for installing from the repository are available here https://github.com/biolab/orange3-imageanalytics/blob/master/README.md 

If you still have issues with proxies please let us know.

**Comment by ndkazu** [comment]
Hello,
I downloaded the modified plugin and gave it a try. unfortunately i got the error bellow:

`Remote server not reachable
Traceback (most recent call last):
  File "C:\Anaconda2\envs\orange3\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 76, in _server_ping_successful
    self._server_connection.ping(bytes(8))
  File "C:\Anaconda2\envs\orange3\lib\site-packages\hypertemp\http20\connection.py", line 214, in ping
    self.connect()
  File "C:\Anaconda2\envs\orange3\lib\site-packages\hypertemp\http20\connection.py", line 374, in connect
    timeout=connect_timeout)
  File "C:\Anaconda2\envs\orange3\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Anaconda2\envs\orange3\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
Remote server not reachable
Traceback (most recent call last):
  File "C:\Anaconda2\envs\orange3\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 76, in _server_ping_successful
    self._server_connection.ping(bytes(8))
  File "C:\Anaconda2\envs\orange3\lib\site-packages\hypertemp\http20\connection.py", line 214, in ping
    self.connect()
  File "C:\Anaconda2\envs\orange3\lib\site-packages\hypertemp\http20\connection.py", line 374, in connect
    timeout=connect_timeout)
  File "C:\Anaconda2\envs\orange3\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Anaconda2\envs\orange3\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
Error
Traceback (most recent call last):
  File "C:\Anaconda2\envs\orange3\lib\site-packages\orangecontrib\imageanalytics\widgets\owimageembedding.py", line 286, in __set_results
    embeddings = f.result()
  File "C:\Anaconda2\envs\orange3\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Anaconda2\envs\orange3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Anaconda2\envs\orange3\lib\site-packages\Orange\widgets\utils\concurrent.py", line 173, in run
    result = func(*args, **kwargs)
  File "C:\Anaconda2\envs\orange3\lib\site-packages\orangecontrib\imageanalytics\widgets\owimageembedding.py", line 238, in run_embedding
    file_paths=paths, image_processed_callback=advance)
  File "C:\Anaconda2\envs\orange3\lib\site-packages\orangecontrib\imageanalytics\image_embedder.py", line 165, in __call__
    return self.from_file_paths(*args, **kwargs)
  File "C:\Anaconda2\envs\orange3\lib\site-packages\orangecontrib\imageanalytics\image_embedder.py", line 224, in from_file_paths
    b_images, image_processed_callback, repeats_counter
  File "C:\Anaconda2\envs\orange3\lib\site-packages\orangecontrib\imageanalytics\image_embedder.py", line 301, in _send_to_server
    body_bytes=image
  File "C:\Anaconda2\envs\orange3\lib\site-packages\orangecontrib\imageanalytics\http2_client.py", line 84, in _send_request
    raise ConnectionError(self._no_conn_err)
ConnectionError: No connection with server, call reconnect_to_server()
`

**Comment by PrimozGodec** [comment]
Is your operating system recognizing the proxy or is it set manually? Orange uses the system proxy settings. 
Can you test if datasets widget works for you (if it works you have proper proxy settings)?

**Comment by ndkazu** [comment]
Hello,
datasets widget is working as expected:
![image](https://user-images.githubusercontent.com/33208377/39741419-d3e19da0-52d4-11e8-99da-2588f78d08b8.png)

I have the following environment variables for the proxy:
HTTP_PROXY, and HTTPS_PROXY.
they allow me to dowload files and using PIP and Conda from the command prompt without entering credential. additionally in Orange3-->settings-->Network, I entered the proxy informations

**Comment by PrimozGodec** [comment]
@ndkazu I will try to source the issue. Can you just let me know how your proxy URL looks like since right now I can not source the issue? Embedders works fine on our test proxy. 
Is it IP e.g. http://100.100.100.100 or domain e.g. http://example.net

**Comment by ndkazu** [comment]
Hello,
my proxy URL is an IP type: http://100.100.100.100

**Comment by asrichardson821** [comment]
Does anyone know what InceptionV3 module code is being executed on the "remote server"? It appears to be a black box, that you cannot verify. Cannot find any detail like this on Orange site.

I am assuming the Image Embedding node is referencing this TF module: https://tfhub.dev/google/tf2-preview/inception_v3/feature_vector/3

Please advise, thanks.

**Comment by PrimozGodec** [comment]
Sorry for the late answer. We are currently running this model http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz of inception V3 embedder. At this link is the simple example of use of this model https://github.com/tensorflow/models/blob/1af55e018eebce03fb61bba9959a04672536107d/tutorials/image/imagenet/classify_image.py

Note: We adapted the model such that we retrieve the penultimate layer of the model as an embedding.

**Comment by ajdapretnar** [comment]
I added explanation to the docs in #153.
