### ISSUE TITLE
Installing Image analytics gives an error message

### ISSUE THREAD

**Issue by bernardofn** [biolab/orange3-imageanalytics#54]
Orange 3.4.1 launched from Anaconda navigator

**Expected behaviour:** 
Install Image Analytics

**Actual:** 
gives an error message (see screenshot and text below). 

![image](https://user-images.githubusercontent.com/29437665/29160528-dd22ee7a-7db2-11e7-9274-b24028633a38.png)

**Error message**
```
Collecting Orange3-ImageAnalytics
  Using cached Orange3-ImageAnalytics-0.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/__init__.py", line 10, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/extern/__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 3013, in _initialize_master_working_set
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2544, in activate
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2118, in declare_namespace
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2058, in _handle_ns
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2087, in _rebuild_mod_path
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2r/rxkf16fx1ddfblxg54484pc40000gn/T/pip-build-24siqd11/Orange3-ImageAnalytics/
```

**Comment by inejc** [comment]
Try updating pip to the latest version and setuptools to 35.0.2 (see https://github.com/pypa/setuptools/issues/885).

**Comment by jerneju** [comment]
Same error as this one https://github.com/biolab/orange3-text/issues/307 .
