### ISSUE TITLE
ImageEmbedder forcefully closes stream

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-imageanalytics#61]
##### Image Analytics version

0.1.7

##### Orange version

3.5.0

##### Expected behavior
ImageEmbedding does not report any errors.

##### Actual behavior
IE continually reports Stream forcefully closed.

##### Steps to reproduce the behavior
Embed images in scripting or see console log.

##### Additional info (worksheets, data, screenshots, ...)

Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/http2_client.py", line 102, in _get_json_response_or_none
    response_raw = self._server_connection.get_response(stream_id)
  File "/Users/ajda/anaconda/envs/o3/lib/python3.5/site-packages/hyper/http20/connection.py", line 312, in get_response
    return HTTP20Response(stream.getheaders(), stream)
  File "/Users/ajda/anaconda/envs/o3/lib/python3.5/site-packages/hyper/http20/stream.py", line 230, in getheaders
    self._recv_cb(stream_id=self.stream_id)
  File "/Users/ajda/anaconda/envs/o3/lib/python3.5/site-packages/hyper/http20/connection.py", line 768, in _recv_cb
    self._get_stream(stream_id)
  File "/Users/ajda/anaconda/envs/o3/lib/python3.5/site-packages/hyper/http20/connection.py", line 289, in _get_stream
    raise StreamResetError("Stream forcefully closed")
hyper.http20.exceptions.StreamResetError: Stream forcefully closed

**Comment by PrimozGodec** [comment]
This error is solved in https://github.com/biolab/orange3-imageanalytics/pull/66

**Comment by kernc** [comment]
So this can be closed?
