### ISSUE TITLE
Error in setting the progress

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-imageanalytics#85]
##### Image Analytics version

0.1.14

##### Orange version

3.9_dev

##### Expected behavior

Setting the progress without error.

##### Actual behavior

Error occurs when setting the progress. Probably overflow of the percentage happens in last few images. 

##### Steps to reproduce the behavior

Run embedders on large set of images

##### Additional info (worksheets, data, screenshots, ...)

Traceback (most recent call last):
  File "/Users/primoz/Documents/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimageembedding.py", line 280, in __set_results
    embeddings = f.result()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Users/primoz/Documents/orange3/Orange/widgets/utils/concurrent.py", line 173, in run
    result = func(*args, **kwargs)
  File "/Users/primoz/Documents/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimageembedding.py", line 232, in run_embedding
    file_paths=paths, image_processed_callback=advance)
  File "/Users/primoz/Documents/orange3-imageanalytics/orangecontrib/imageanalytics/image_embedder.py", line 157, in __call__
    return self.from_file_paths(*args, **kwargs)
  File "/Users/primoz/Documents/orange3-imageanalytics/orangecontrib/imageanalytics/image_embedder.py", line 216, in from_file_paths
    b_images, image_processed_callback, repeats_counter
  File "/Users/primoz/Documents/orange3-imageanalytics/orangecontrib/imageanalytics/image_embedder.py", line 304, in _send_to_server
    image_processed_callback
  File "/Users/primoz/Documents/orange3-imageanalytics/orangecontrib/imageanalytics/image_embedder.py", line 397, in _get_responses_from_server
    image_processed_callback(embeddings[-1] is not None)
  File "/Users/primoz/Documents/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimageembedding.py", line 221, in advance
    set_progress(next(ticks))
StopIteration

**Comment by PrimozGodec** [comment]
Fixed in https://github.com/biolab/orange3-imageanalytics/pull/97
